# Generated by Django 4.2.7 on 2023-12-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
